# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mininb',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/mininb',
                'lib_path': 'mininb'},
  'syms': {'mininb.core': {'mininb.core.foo': ('core.html#foo', 'mininb/core.py')}}}
